name: Build-PDF
on: push
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
      - uses: WtfJoke/setup-tectonic@v2
      - run: tectonic main.tex --synctex --keep-intermediates --outdir build
      - uses: actions/upload-artifact@v4
        with:
          name: FreeWill-PDF
          path: build/main.pdf
